### ISSUE TITLE
Не обрабатывает страну Тайвань

### ISSUE THREAD

**Issue by alexfilimon** [Olegas/3ndfl-report-maker#2]
При запуске не узнавал страну тайвань, потому что в библиотеке `i18n-iso-countries` страна называется по другому.

Пришлось добавлять страшную проверку:

![photo_2022-05-02 13 30 31](https://user-images.githubusercontent.com/19904867/166220850-aff11e95-ce07-4e43-8f16-8258635a4237.jpeg)

**Comment by Olegas** [comment]
https://github.com/michaelwittig/node-i18n-iso-countries/pull/293

**Comment by Olegas** [comment]
Исправили в node-i18n-iso-countries, нужно обновить зависимости
